export const governoratesData = [
  { id: "1", governorate_name_ar: "Andhra Pradesh", governorate_name_en: "Andhra Pradesh" },
  { id: "2", governorate_name_ar: "Arunachal Pradesh", governorate_name_en: "Arunachal Pradesh" },
  { id: "3", governorate_name_ar: "Assam", governorate_name_en: "Assam" },
  { id: "4", governorate_name_ar: "Bihar", governorate_name_en: "Bihar" },
  { id: "5", governorate_name_ar: "Chhattisgarh", governorate_name_en: "Chhattisgarh" },
  { id: "6", governorate_name_ar: "Goa", governorate_name_en: "Goa" },
  { id: "7", governorate_name_ar: "Gujarat", governorate_name_en: "Gujarat" },
  { id: "8", governorate_name_ar: "Haryana", governorate_name_en: "Haryana" },
  { id: "9", governorate_name_ar: "Himachal Pradesh", governorate_name_en: "Himachal Pradesh" },
  { id: "10", governorate_name_ar: "Jharkhand", governorate_name_en: "Jharkhand" },
  { id: "11", governorate_name_ar: "Karnataka", governorate_name_en: "Karnataka" },
  { id: "12", governorate_name_ar: "Kerala", governorate_name_en: "Kerala" },
  { id: "13", governorate_name_ar: "Madhya Pradesh", governorate_name_en: "Madhya Pradesh" },
  { id: "14", governorate_name_ar: "Maharashtra", governorate_name_en: "Maharashtra" },
  { id: "15", governorate_name_ar: "Manipur", governorate_name_en: "Manipur" },
  { id: "16", governorate_name_ar: "Meghalaya", governorate_name_en: "Meghalaya" },
  { id: "17", governorate_name_ar: "Mizoram", governorate_name_en: "Mizoram" },
  { id: "18", governorate_name_ar: "Nagaland", governorate_name_en: "Nagaland" },
  { id: "19", governorate_name_ar: "Odisha", governorate_name_en: "Odisha" },
  { id: "20", governorate_name_ar: "Punjab", governorate_name_en: "Punjab" },
  { id: "21", governorate_name_ar: "Rajasthan", governorate_name_en: "Rajasthan" },
  { id: "22", governorate_name_ar: "Sikkim", governorate_name_en: "Sikkim" },
  { id: "23", governorate_name_ar: "Tamil Nadu", governorate_name_en: "Tamil Nadu" },
  { id: "24", governorate_name_ar: "Telangana", governorate_name_en: "Telangana" },
  { id: "25", governorate_name_ar: "Tripura", governorate_name_en: "Tripura" },
  { id: "26", governorate_name_ar: "Uttar Pradesh", governorate_name_en: "Uttar Pradesh" },
  { id: "27", governorate_name_ar: "Uttarakhand", governorate_name_en: "Uttarakhand" },
  { id: "28", governorate_name_ar: "West Bengal", governorate_name_en: "West Bengal" },
  { id: "29", governorate_name_ar: "Andaman and Nicobar Islands", governorate_name_en: "Andaman and Nicobar Islands" },
  { id: "30", governorate_name_ar: "Chandigarh", governorate_name_en: "Chandigarh" },
  { id: "31", governorate_name_ar: "Dadra and Nagar Haveli and Daman and Diu", governorate_name_en: "Dadra and Nagar Haveli and Daman and Diu" },
  { id: "32", governorate_name_ar: "Delhi", governorate_name_en: "Delhi" },
  { id: "33", governorate_name_ar: "Lakshadweep", governorate_name_en: "Lakshadweep" },
  { id: "34", governorate_name_ar: "Puducherry", governorate_name_en: "Puducherry" },
];